# Options for analysis running.
run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 1m

linters-settings:
  errcheck:
    check-type-assertions: true # default false
    check-blank: false # default false
    ignore: "fmt:.*" # default fmt:.*
    exclude-functions: [] # see https://github.com/kisielk/errcheck#excluding-functions for details # default []
  govet:
    enable-all: true
    disable:
      - fieldalignment # too strict
    settings:
      shadow:
        strict: true # default false
  staticcheck:
    go: "1.17"
    checks: ["*"]

linters:
  disable-all: true
  enable:
    - errcheck
    - staticcheck
    - govet
    - gosimple
    - ifshort

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
output:
  uniq-by-line: false # default true
